# Generated by Django 5.1 on 2024-08-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=225, verbose_name='username')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('customer_type', models.IntegerField(choices=[(0, 'student'), (1, 'lecturer')], default=0, verbose_name='customer_type')),
            ],
        ),
    ]
