# Generated by Django 5.1 on 2024-08-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionbank',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('option1', models.CharField(max_length=255)),
                ('option2', models.CharField(max_length=255)),
                ('option3', models.CharField(max_length=255)),
                ('option4', models.CharField(max_length=255)),
                ('answer', models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option4', 'option4'), ('option4', 'option4')], max_length=255)),
                ('level', models.CharField(choices=[('easy', 'easy'), ('middle', 'middle'), ('hard', 'hard')], max_length=10)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
