# Generated by Django 5.1 on 2024-08-27 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_questionbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_name', models.CharField(max_length=255)),
                ('Question_number', models.PositiveBigIntegerField()),
                ('total_marks', models.PositiveIntegerField()),
                ('time', models.IntegerField()),
            ],
            options={
                'db_table': 'Assignment',
            },
        ),
        migrations.AlterModelTable(
            name='questionbank',
            table='Questionbank',
        ),
        migrations.AddField(
            model_name='questionbank',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.assignment'),
        ),
    ]
