# Generated by Django 5.1 on 2024-08-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_assignment_alter_questionbank_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='answer',
            field=models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4')], max_length=255),
        ),
    ]
