# Generated by Django 5.1 on 2024-09-04 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_studentanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionbank',
            old_name='answer',
            new_name='answers',
        ),
    ]
