# Generated by Django 5.1 on 2024-09-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_answer_questionbank_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='answers',
        ),
        migrations.AddField(
            model_name='questionbank',
            name='answer',
            field=models.CharField(choices=[('Option1', 'Option1'), ('Option2', 'Option2'), ('Option3', 'Option3'), ('Option4', 'Option4')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
