# Generated by Django 5.1 on 2024-09-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_questionbank_answers_questionbank_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='Question_number',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='assignment',
            name='mechanism_type',
            field=models.IntegerField(choices=[(0, 'random'), (1, 'fixed')], default=0, verbose_name='customer_type'),
        ),
    ]
