# Generated by Django 5.1 on 2024-10-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_studentanswer_studentresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='mechanism_type',
            field=models.IntegerField(choices=[(0, 'random'), (1, 'fixed'), (2, 'dynamic')], default=0, verbose_name='customer_type'),
        ),
    ]
