# Generated by Django 5.1 on 2024-10-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_assignment_mechanism_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='option1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='option2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='option3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='option4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
