# Generated by Django 5.1 on 2024-10-22 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_questionbank_option1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='time',
        ),
    ]
