# Generated by Django 5.1 on 2024-10-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_questionbank_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='answer',
            field=models.CharField(choices=[('Option1', 'Option1'), ('Option2', 'Option2'), ('Option3', 'Option3'), ('Option4', 'Option4')], max_length=200),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
