# Generated by Django 5.1 on 2024-10-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_questionbank_answer_alter_studentanswer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='is_timed_out',
            field=models.BooleanField(default=False),
        ),
    ]
