# Generated by Django 5.1 on 2024-10-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_studentanswer_is_timed_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='is_timed_out',
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='answer',
            field=models.CharField(max_length=200),
        ),
    ]
