# Generated by Django 5.1 on 2024-10-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_studentanswer_is_timed_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
