# Generated by Django 5.1 on 2024-10-22 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_studentanswer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='assignment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.assignment'),
            preserve_default=False,
        ),
    ]
