# Generated by Django 5.1 on 2024-10-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_studentanswer_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
